[workspace]
members = [
    "crates/token",
    "crates/lexer",
    "crates/common",
    "crates/compiler",
    "crates/parser",
    "crates/ast",
    "crates/runtime",
    "toyjs"
]

[profile.release]
debug = true
