[package]
name = "toyjs_web"
version = "0.2.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.58"
wee_alloc = { version = "0.4.4", optional = true }
toyjs = { path = "../toyjs" }

