[package]
name = "toyjs_ast"
version = "0.1.0"
authors = ["Mees Delzenne <mees.delzenne@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = { version = "3.4.0", features = ["boxed","collections"]}
common = { package="toyjs_common",path = "../common/" }
derivative = "2.2.0"
