[package]
name = "toyjs_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
untagged = []


[dependencies]
unicode-ident = "1.0.8"
