[package]
name = "toyjs_common"
version = "0.1.0"
authors = ["Mees Delzenne <mees.delzenne@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"
bumpalo = { version = "3.9.1", features = ["boxed","collections"] }
static_assertions = "1.1.0"
