[package]
name = "toyjs_vm"
version = "0.1.0"
authors = ["Mees Delzenne <mees.delzenne@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { package="toyjs_common",path = "../common/" }
token = { package="toyjs_token",path = "../token/" }
lexer = { package="toyjs_lexer",path = "../lexer/" }
bitflags = "1.3.2"
# ast = { package="toyjs_ast",path = "../ast/" }

[features]
tagged-union = []
dump-gc-trace = []
parallel = []
